name: Dynamic Runner Selection

on:
  workflow_dispatch:
    inputs:
      choice:
        description: 'Choose the runner'
        required: true
        default: 'linux'

jobs:
  run-based-on-choice:
    runs-on: ${{ github.event.inputs.choice == 'android' && 'macos-latest' || github.event.inputs.choice == 'windows' && 'windows-latest' || 'ubuntu-latest' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run your task
        run: |
          # Your task to run based on the input choice
          echo "Running on ${{ github.event.inputs.choice }} runner"
