name: Dynamic Runner Selection

on:
  workflow_dispatch:
    inputs:
      choice:
        description: 'Choose the runner'
        required: true
        type: choice
        options: APP, AAB, IPA, MAC, EXE, LINUX, Custom

jobs:
  run-based-on-choice:
    runs-on: ${{ github.event.inputs.choice == 'APP' && 'macos-latest' || github.event.inputs.choice == 'AAB' && 'macos-latest' || github.event.inputs.choice == 'IPA' && 'macos-latest' || github.event.inputs.choice == 'MAC' && 'macos-latest' || github.event.inputs.choice == 'EXE' && 'windows-latest' || github.event.inputs.choice == 'LINUX' && 'ubuntu-latest' || github.event.inputs.choice == 'Custom' && 'ubuntu-latest' || 'ubuntu-latest' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run your task
        run: |
          # Your task to run based on the input choice
          echo "Running on ${{ github.event.inputs.choice }} runner"
